TEMPLATEROOT = ..

# compilation flags for gdb

CFLAGS  = -O1 -g
ASFLAGS = -g 

# object files

OBJS=  $(STARTUP) PWM_output.o
#extra stuff
OBJS+=	stm32f10x_gpio.o stm32f10x_rcc.o stm32f10x_tim.o


# include common make file

include $(TEMPLATEROOT)/Makefile.common


