TEMPLATEROOT = ..

# compilation flags for gdb

CFLAGS  = -O1 -g
ASFLAGS = -g 

# object files

OBJS=  $(STARTUP) blinking_lights.o

# include common make file

include $(TEMPLATEROOT)/Makefile.common


